# deploys mosquitto service (on the server)
apiVersion: v1
kind: Service
metadata:
  name: serv-mosquitto-service
  labels:
    run: mosquitto
spec:
  type: NodePort
  ports:
  - nodePort: 32211
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto