## CHECK AGAINST THIS CODE 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: processor
        image: seankoval/processor:v3
        env: 
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: username
        - name: AWS_SECRET_KEY #AWS_SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: aws-secret
              key: password